version: '3.8'
services:
  credit-loans-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-credit-loans-service
    restart: always
    ports:
      - 8085:8085
    networks:
      bank_network:
        aliases:
          - app_subnet
        #ipv4_address: 172.20.0.4
networks:
  bank_network:
    name: app_subnet
    external: true